universe              = vanilla
request_disk          = 2GB
request_memory        = 5GB
executable            = script.sh
should_transfer_files = YES
transfer_input_files = script.sh,PFComm_2018A.txt, x509up, /work/submit/akanugan/SUEP_NanoAOD/CMSSW_10_6_26/src/PhysicsTools/SUEPScouting
output               = ../../../logs/job.$(Cluster).$(Process).out
error                = ../../../logs/job.$(Cluster).$(Process).err
log                  = ../../../logs/job.$(Cluster).$(Process).log
when_to_transfer_output = ON_EXIT
on_exit_remove        = (ExitBySignal == False) && (ExitCode == 0)
max_retries           = 3
use_x509userproxy     = True
x509userproxy         = /home/submit/akanugan/x509up
+AccountingGroup      = "analysis.akanugan"
Requirements          = ( BOSCOCluster =!= "t3serv008.mit.edu" && BOSCOCluster =!= "ce03.cmsaf.mit.edu" && BOSCOCluster =!= "eofe8.mit.edu")
+DESIRED_Sites        = "T2_US_MIT"
+JobFlavour           = "workday"
requirements = (OpSysAndVer =?= "CentOS7" || OpSysAndVer =?= "RedHat7")
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel7"
+SingularityBindCVMFS = True
+SingularityBind = "$(PWD):/srv"

# Arguments: jobnum input_file output_file cmssw_version
arguments             = $(Process) $(infile) $(outfile) CMSSW_10_6_26

queue infile,outfile from PFComm_2018A.txt